const Menu = [
  {
    id: 1,
    name: "Classic Maggi",
    category: "Breakfast",
    price: 120,
    image: "images/maggie-3.jpg",
    description: "Hot and tasty 2-minute Maggi with a blend of spices and flavor.",
  },
  {
    id: 2,
    name: "Cheese Maggi",
    category: "Breakfast",
    price: 150,
    image: "images/maggie-4.png",
    description: "Creamy cheese melted into soft noodles for the perfect comfort meal.",
  },
  {
    id: 3,
    name: "Veggie Delight Maggi",
    category: "Breakfast",
    price: 140,
    image: "images/plain-maggie-1.png",
    description: "Loaded with fresh vegetables and a hint of herbs — healthy and yummy!",
  },
  {
    id: 4,
    name: "Spicy Masala Maggi",
    category: "Breakfast",
    price: 130,
    image: "images/masala-maggie-2.jpg",
    description: "Fiery and flavorful Maggi for spice lovers who like it hot!",
  },
  
{
    id: 5,
    name: "Full loaded plater",
    category: "Lunch",
    price: 280,
    image: "images/img5.webp",
    description: "Rich and creamy paneer curry cooked with butter and aromatic spices.",
  },
  {
    id: 6,
    name: "vegetarian mustard",
    category: "Lunch",
    price: 350,
    image: "images/img6.jpg",
    description: "Fragrant basmati rice layered with spiced chicken and herbs.",
  },
  {
    id: 7,
    name: "Beaf burger",
    category: "Lunch",
    price: 300,
    image: "images/img7.jpg",
    description: "A wholesome Indian platter with curries, rice, and roti.",
  },
  {
    id: 8,
    name: "Dal Tadka",
    category: "Lunch",
    price: 180,
    image: "images/img8.jpg",
    description: "Yellow lentils tempered with ghee, garlic, and flavorful spices.",
  },
  {
    id: 9,
    name: "Chole Bhature",
    category: "Lunch",
    price: 220,
    image: "images/img9.jpeg",
    description: "Fluffy bhature served with spicy chickpea curry — North Indian favorite.",
  },

  // 🍽 Dinner
  {
    id: 10,
    name: "Butter Chicken",
    category: "Dinner",
    price: 350,
    image: "images/img10.jpg",
    description: "Juicy chicken pieces cooked in creamy tomato gravy with butter.",
  },
  {
    id: 11,
    name: "Saucy Lasagnea",
    category: "Dinner",
    price: 400,
    image: "images/img11.jpg",
    description: "Slow-cooked mutton with rich spices for a royal dinner experience.",
  },
  {
    id: 12,
    name: "Paneer Tikka",
    category: "Dinner",
    price: 250,
    image: "images/img12.jpeg",
    description: "Grilled paneer cubes marinated in yogurt and spices — smoky and tasty.",
  },
  {
    id: 13,
    name: "Full loaded pasta",
    category: "Dinner",
    price: 220,
    image: "images/img13.jpg",
    description: "Flavored basmati rice with cumin seeds — best paired with curry.",
  },
  {
    id: 14,
    name: "Fish Fry",
    category: "Dinner",
    price: 380,
    image: "images/img14.webp",
    description: "Crispy fried fish marinated with Indian spices — crunchy outside, tender inside.",
  },

  // 🍟 Snacks
  {
    id: 15,
    name: "Mini burgers",
    category: "Snacks",
    price: 100,
    image: "images/img15.jpg",
    description: "Crispy golden fries served with tangy ketchup or spicy mayo.",
  },
  {
    id: 16,
    name: "chicken'n Shapes",
    category: "Snacks",
    price: 80,
    image: "images/img16.jpeg",
    description: "Crispy pastry stuffed with spicy potatoes and peas — a classic snack.",
  },
  {
    id: 17,
    name: "chicken nuggets",
    category: "Snacks",
    price: 120,
    image: "images/img17.webp",
    description: "Toasted sandwich filled with fresh veggies and chutney.",
  },
  {
    id: 18,
    name: "Spring Rolls",
    category: "Snacks",
    price: 150,
    image: "images/img18.webp",
    description: "Crispy rolls packed with mixed veggies and served with hot sauce.",
  },
  {
    id: 19,
    name: "Crunchy'n snacks",
    category: "Snacks",
    price: 180,
    image: "images/img19.jpeg",
    description: "Creamy white sauce pasta topped with cheese and herbs.",
  },
  {
    id: 20,
    name: "Salamanin",
    category: "Snacks",
    price: 200,
    image: "images/img20.jpeg",
    description: "Soft bun with juicy patty, cheese, and veggies — a perfect evening bite.",
  },
];

export default Menu;